name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ .github/** ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'This is the environment we will deploy to.'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is was triggered by the event: ${{ github.event_name }}"
          echo "The current branch is ${{ github.ref }} of the repository ${{ github.repository }}"

      - uses: actions/checkout@v6.0.2

      - name: List all teh files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Test
      steps:
        - run: echo "Testing..."

    Load-Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Load-Test
      steps:
        - run: echo "Testing..."
          sleep 15

    Production:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: [Test, Load-Test]
      environment:
        name: Production
        url: https://writeabout.net
      steps:
        - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
